### ISSUE TITLE
Are all steps idempotent?

### ISSUE THREAD

**Issue by hwine** [mozilla/releasewarrior#3]
I admit to being way behind on the state of release duty, but in the old days, we sometimes "collided" on handling commands manually.
- Does releasewarrior ensure all tasks are idempotent? Or will that still be up to humans to coordinate?
- If 2 folks perform a task at the same time, does that produce a merge conflict in the data files? How do folks correct?

Fair to say the above are out of scope, but should give that some mention in the docs, imo.

**Comment by lundjordan** [comment]
sorry I missed this earlier. official releasewarrior is now at  https://github.com/mozilla/releasewarrior

to protect against mistakes, I have 

1) tried to design it so that each command is idempotent. e.g. run the same command twice and both the data and wiki files should not change. nor should there be a commit at the end. if that behavior isn't observed, that's a bug :)

2) warn if your local repo is dirty before running a command, and abort if your local repo is behind origin/master. this makes git less distributed but it acts as a blocker for merge conflicts + missing updates from other relengers.

**Comment by hwine** [comment]
Sounds good to me! Especially (2) -- worthy of being documented, imho.
